project_id = "wdqeqgaoqndoacjkiisf"

[functions.client-auth]
verify_jwt = false

[functions.video-proxy]
verify_jwt = false

[functions.import-m3u]
verify_jwt = false

[functions.channel-ping]
verify_jwt = false
